version: '3.5'

services:
    nginx:
        build: ./docker-files/nginx
        volumes:
            - .:/var/www
        links:
            - "php-fpm:php-fpm"
        depends_on:
            - php-fpm
#            - composer-install
        environment:
            - DOMAIN=${DOMAIN}
        labels:
            - "traefik.http.routers.symfony.rule=Host(`${DOMAIN}`)"
        volumes:
            - ./public:/var/www/public
        networks:
            - traefik-net
    php-fpm:
        build: ./docker-files/php-fpm
#        depends_on:
#            - postgres
        volumes:
            - .:/var/www
        networks:
            - traefik-net
        environment:
            - XDEBUG_HOST=${XDEBUG_HOST}
            - XDEBUG_PORT=${XDEBUG_PORT}
            - XDEBUG_IDE_KEY=${XDEBUG_IDE_KEY}

#    composer-install:
#        image: composer:1.6.5
#        command: install
#        volumes:
#            - .:/app

#    postgres:
#        image: postgres:9.6
#        environment:
#            - POSTGRES_USER=${POSTGRES_USER}
#            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
#            - POSTGRES_DB=${POSTGRES_DB}

networks:
    traefik-net:
        external: true
